import type { ComplianceRule } from '../../shared/types.js';

function genId() {
  return `rule_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

const now = new Date().toISOString();

export const BUILTIN_RULES: ComplianceRule[] = [
  {
    id: 'builtin_privacy_data_collection',
    name: '隐私政策-数据收集说明',
    description: '隐私政策文档必须包含数据收集说明章节',
    type: 'regex',
    severity: 'critical',
    category: 'privacy',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(数据收集|信息收集|收集.{0,10}(个人|用户|信息|数据))', flags: 'i' },
    ],
    fixGuidance: '请在隐私政策中添加"数据收集"或"信息收集"相关章节，明确说明收集哪些用户数据以及收集目的。',
    tags: ['隐私政策', '必填项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_privacy_data_usage',
    name: '隐私政策-数据使用说明',
    description: '隐私政策必须说明数据使用方式',
    type: 'regex',
    severity: 'critical',
    category: 'privacy',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(使用.{0,10}(数据|信息)|数据使用|信息使用|使用目的|用途)', flags: 'i' },
    ],
    fixGuidance: '请添加数据使用说明章节，详细描述数据将被如何使用，例如用于提供服务、改进产品、个性化推荐等。',
    tags: ['隐私政策', '必填项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_privacy_third_party',
    name: '隐私政策-第三方共享',
    description: '隐私政策必须说明是否与第三方共享数据',
    type: 'regex',
    severity: 'warning',
    category: 'privacy',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(第三方|共享|披露|提供给.{0,10}(第三方|其他公司))', flags: 'i' },
    ],
    fixGuidance: '建议添加关于第三方数据共享的说明，包括共享对象、共享内容和共享目的。',
    tags: ['隐私政策', '建议项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_privacy_user_rights',
    name: '隐私政策-用户权利',
    description: '隐私政策应说明用户的权利（访问、删除、更正等）',
    type: 'regex',
    severity: 'warning',
    category: 'privacy',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(用户权利|您的权利|访问.{0,5}(个人|信息)|删除.{0,5}(账户|信息)|更正|修改个人信息)', flags: 'i' },
    ],
    fixGuidance: '建议添加用户权利说明，包括访问个人信息、更正错误信息、删除账户等权利的行使方式。',
    tags: ['隐私政策', '建议项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_privacy_contact',
    name: '隐私政策-联系方式',
    description: '隐私政策应提供隐私问题的联系方式',
    type: 'regex',
    severity: 'info',
    category: 'privacy',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(联系我们|联系方式|privacy@|隐私.{0,5}(联系|邮箱|电话))', flags: 'i' },
    ],
    fixGuidance: '建议添加隐私问题的联系方式，如专门的隐私邮箱或联系渠道。',
    tags: ['隐私政策', '建议项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_contract_sign_date',
    name: '合同-签署日期条款',
    description: '合同文档必须包含签署日期条款',
    type: 'regex',
    severity: 'critical',
    category: 'contract',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(签署日期|签订日期|签约日期|订立日期|于.{0,10}(年|月|日).{0,10}签订|Date of Signing|Signed on)', flags: 'i' },
    ],
    fixGuidance: '请在合同中添加签署日期条款，明确合同签订的具体日期。',
    tags: ['合同', '必填项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_contract_party_info',
    name: '合同-甲乙双方信息',
    description: '合同必须包含甲乙双方完整信息',
    type: 'regex',
    severity: 'critical',
    category: 'contract',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(甲方|乙方|Party A|Party B|卖方|买方|发包方|承包方)', flags: 'i' },
    ],
    fixGuidance: '请确保合同中明确列出甲乙双方（或各方）的完整信息，包括名称、地址、法定代表人等。',
    tags: ['合同', '必填项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_contract_payment',
    name: '合同-付款条款',
    description: '合同应包含明确的付款条款',
    type: 'regex',
    severity: 'warning',
    category: 'contract',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(付款|支付|款项|合同金额|价款|费用|Payment|Amount)', flags: 'i' },
    ],
    fixGuidance: '建议添加明确的付款条款，包括金额、付款方式、付款时间和付款条件。',
    tags: ['合同', '建议项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_contract_termination',
    name: '合同-终止条款',
    description: '合同应包含终止/解除条款',
    type: 'regex',
    severity: 'warning',
    category: 'contract',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(终止|解除|违约|解除合同|终止合同|Termination|Breach)', flags: 'i' },
    ],
    fixGuidance: '建议添加合同终止和解除条款，明确终止条件、违约责任和提前终止的处理方式。',
    tags: ['合同', '建议项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_contract_dispute',
    name: '合同-争议解决',
    description: '合同应包含争议解决条款',
    type: 'regex',
    severity: 'info',
    category: 'contract',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(争议|纠纷|仲裁|诉讼|管辖法院|争议解决|Dispute Resolution|Arbitration)', flags: 'i' },
    ],
    fixGuidance: '建议添加争议解决条款，明确争议的解决方式（协商、调解、仲裁、诉讼）和管辖法院。',
    tags: ['合同', '建议项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_tech_hardcoded_password',
    name: '技术文档-硬编码密码检测',
    description: '技术文档中禁止出现硬编码密码',
    type: 'regex',
    severity: 'critical',
    category: 'technical',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(password|passwd|pwd)\\s*[:=]\\s*["\']?[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{}|;:,.<>?]{6,}["\']?', flags: 'gi' },
      { pattern: '(密码|口令)\\s*[:：]\\s*[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{}|;:,.<>?]{6,}', flags: 'gi' },
      { pattern: 'api[_-]?key\\s*[:=]\\s*["\']?[a-zA-Z0-9]{20,}["\']?', flags: 'gi' },
      { pattern: 'secret\\s*[:=]\\s*["\']?[a-zA-Z0-9]{20,}["\']?', flags: 'gi' },
    ],
    fixGuidance: '请移除文档中的硬编码密码、API密钥或密钥。使用占位符（如 <PASSWORD>、<API_KEY>）或环境变量引用代替。',
    tags: ['安全', '技术文档', '禁止项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_tech_hardcoded_token',
    name: '技术文档-硬编码Token检测',
    description: '技术文档中禁止出现硬编码的访问令牌',
    type: 'regex',
    severity: 'critical',
    category: 'technical',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(Bearer|Token)\\s+[A-Za-z0-9\\-_=]{20,}\\.[A-Za-z0-9\\-_=]{20,}\\.[A-Za-z0-9\\-_=]+', flags: 'gi' },
      { pattern: 'gh[pousr]_[A-Za-z0-9]{36,}', flags: 'gi' },
      { pattern: 'sk-[A-Za-z0-9]{20,}', flags: 'gi' },
      { pattern: 'eyJ[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9._-]+', flags: 'gi' },
    ],
    fixGuidance: '请移除文档中的硬编码Token、JWT或访问凭证。使用占位符或引用安全存储机制。',
    tags: ['安全', '技术文档', '禁止项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_tech_private_ip',
    name: '技术文档-敏感IP地址检测',
    description: '技术文档中建议避免暴露内网IP地址',
    type: 'regex',
    severity: 'warning',
    category: 'technical',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '\\b192\\.168\\.\\d{1,3}\\.\\d{1,3}\\b', flags: 'g' },
      { pattern: '\\b10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b', flags: 'g' },
      { pattern: '\\b172\\.(1[6-9]|2\\d|3[01])\\.\\d{1,3}\\.\\d{1,3}\\b', flags: 'g' },
    ],
    fixGuidance: '建议对文档中的内网IP地址进行脱敏处理，使用 <INTERNAL_IP> 等占位符代替。',
    tags: ['安全', '技术文档', '建议项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_tech_email_leak',
    name: '技术文档-敏感邮箱检测',
    description: '技术文档中建议避免暴露内部员工邮箱',
    type: 'regex',
    severity: 'info',
    category: 'technical',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '[a-zA-Z0-9._%+-]+@(?!example\\.com|test\\.com|company\\.com)[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}', flags: 'gi' },
    ],
    fixGuidance: '建议使用通用示例邮箱（如 user@example.com）代替真实邮箱地址。',
    tags: ['隐私', '技术文档', '建议项'],
    isBuiltin: true,
  },
  {
    id: 'builtin_tech_todo_comment',
    name: '技术文档-TODO标记',
    description: '文档中存在未完成的TODO标记',
    type: 'regex',
    severity: 'info',
    category: 'technical',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '(TODO|FIXME|HACK|XXX)[:：\\s]', flags: 'gi' },
    ],
    fixGuidance: '文档中存在待处理标记，建议在发布前完成相关内容或移除标记。',
    tags: ['技术文档', '完整性'],
    isBuiltin: true,
  },
  {
    id: 'builtin_general_structure_heading',
    name: '通用-文档结构完整性',
    description: '文档应包含至少一个一级标题',
    type: 'regex',
    severity: 'warning',
    category: 'general',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '^#\\s+', flags: 'm' },
    ],
    fixGuidance: '建议添加文档的一级标题（# 标题），以确保文档结构完整。',
    tags: ['通用', '结构'],
    isBuiltin: true,
  },
  {
    id: 'builtin_general_broken_link',
    name: '通用-损坏链接检测',
    description: '检查文档中可能存在的链接格式问题',
    type: 'regex',
    severity: 'warning',
    category: 'general',
    status: 'active',
    version: 1,
    createdAt: now,
    updatedAt: now,
    patterns: [
      { pattern: '\\[([^\\]]+)\\]\\(\\s*\\)', flags: 'g' },
      { pattern: '\\[([^\\]]+)\\]\\([^)\\s]*(\\s|$)', flags: 'gm' },
    ],
    fixGuidance: '请检查文档中的链接格式，确保所有链接都有有效的URL。',
    tags: ['通用', '链接'],
    isBuiltin: true,
  },
];

export function createRuleFromTemplate(template: Partial<ComplianceRule>): ComplianceRule {
  const now = new Date().toISOString();
  return {
    id: template.id || genId(),
    name: template.name || '未命名规则',
    description: template.description || '',
    type: template.type || 'regex',
    severity: template.severity || 'warning',
    category: template.category || 'general',
    status: template.status || 'draft',
    version: template.version || 1,
    createdAt: template.createdAt || now,
    updatedAt: now,
    patterns: template.patterns,
    astConditions: template.astConditions,
    customScript: template.customScript,
    fixGuidance: template.fixGuidance || '请参考相关合规要求进行修复。',
    appliesToFileTypes: template.appliesToFileTypes,
    tags: template.tags,
    isBuiltin: false,
  };
}
